// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package credit

import ()

type Credit struct {
	ID            int32
	Ssrn          int32
	ProjectID     string
	Std           string
	Methodology   string
	Region        string
	Storagemethod string
	Method        string
	Emissiontype  string
	Catergory     string
	Uri           string
	Beneficiary   string
}
