// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package credit

import (
	"context"
)

const getCreditBySSRN = `-- name: GetCreditBySSRN :one
SELECT id, ssrn, project_id, std, methodology, region, storagemethod, method, emissiontype, catergory, uri, beneficiary FROM credits WHERE ssrn = $1
`

func (q *Queries) GetCreditBySSRN(ctx context.Context, ssrn int32) (*Credit, error) {
	row := q.db.QueryRow(ctx, getCreditBySSRN, ssrn)
	var i Credit
	err := row.Scan(
		&i.ID,
		&i.Ssrn,
		&i.ProjectID,
		&i.Std,
		&i.Methodology,
		&i.Region,
		&i.Storagemethod,
		&i.Method,
		&i.Emissiontype,
		&i.Catergory,
		&i.Uri,
		&i.Beneficiary,
	)
	return &i, err
}
